### ISSUE TITLE
Adding file returns non ndjson

### ISSUE THREAD

**Issue by travisperson** [ipfs/go-ipfs#2109]
This was produced with `js-ipfs-api v2.10.1` connected to `ipfs version 0.4.0-dev`

```javascript
ipfs.add(new Buffer("hello"), function (err, dat) {
    console.log(err, dat)
})
```

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Could not parse row {...
```

```
 => POST /api/v0/add?stream-channels=true HTTP/1.1
 => User-Agent: /node-ipfs-api/2.10.1/
 => Content-Type: multipart/form-data; boundary=7fx0z9h714utbj4ici98rn94zo3fecdiwarvbz5ufx7jh5min0j640azqguv7vi
 => Host: localhost:5001
 => Connection: close
 => Transfer-Encoding: chunked
 => 
 => 43
 => --7fx0z9h714utbj4ici98rn94zo3fecdiwarvbz5ufx7jh5min0j640azqguv7vi
 => 
 => 57
 => Content-Disposition: file; filename=""
 => Content-Type: application/octet-stream
 => 
 => hello
 => 45
 => 
 => --7fx0z9h714utbj4ici98rn94zo3fecdiwarvbz5ufx7jh5min0j640azqguv7vi--
 => 0
 => 
<=  HTTP/1.1 200 OK
<=  Content-Type: application/json
<=  Trailer: X-Stream-Error
<=  Transfer-Encoding: chunked
<=  X-Chunked-Output: 1
<=  Date: Mon, 21 Dec 2015 07:20:18 GMT
<=  Connection: close
<=  Transfer-Encoding: chunked
<=  
<=  7b
<=  {
<=    "Name": "QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX",
<=    "Hash": "QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX"
<=  }
<=  

```

**Comment by travisperson** [comment]
This commit probably need to be pulled into `0.4.0` 891a8d7656174401bc17c71acc52d4e93c4fe8eb

**Comment by whyrusleeping** [comment]
ah yeah, thats been fixed on 0.4.0 since the last rebase. Good catch. I'll try and get to the rebase this week.

**Comment by diasdavid** [comment]
@travisperson this was fixed on 0.4.0 and we have a branch on js-ipfs-api specific for 0.4.0, could you try with that one? https://github.com/ipfs/js-ipfs-api/pull/74 thank you :)

**Comment by RichardLitt** [comment]
@travisperson Curious why this was closed?

**Comment by tinybike** [comment]
I'm still experiencing this issue; js-ipfs-api is unusable for me at the moment in Nodejs.  (Whatever is causing this bug doesn't affect the distributable.)
