### ISSUE TITLE
too many open files in v0.4.2

### ISSUE THREAD

**Issue by peersafe** [ipfs/go-ipfs#2739]
Initializing daemon...
Swarm listening on /ip4/114.242.47.102/tcp/1113
Swarm listening on /ip4/114.242.47.102/tcp/33506
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.235/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
16:10:13.428 ERROR     flatfs: too many open files, retrying in %dms0 flatfs.go:127
16:10:13.429 ERROR     flatfs: too many open files, retrying in %dms100 flatfs.go:127
16:10:13.530 ERROR     flatfs: too many open files, retrying in %dms200 flatfs.go:127
16:10:37.905 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:130
16:10:57.901 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:130

**Comment by whyrusleeping** [comment]
what platform are you on? (os, architecture) and what are you using the daemon for, what does your workload look like?

**Comment by peersafe** [comment]
On Mac OSX 10.11.4, try to get some files several times, the error will occurred, but not always.

**Comment by whyrusleeping** [comment]
@peersafe try running the daemon as `ipfs daemon --manage-fdlimit`

**Comment by whyrusleeping** [comment]
@peersafe this should be better now. I made that manage-fdlimit option default to true.

**Comment by briansoule** [comment]
Still getting this on MacOS 10.12.6

**Comment by Kubuxu** [comment]
Try updating to newest master. New bug causing this was just fixed.

**Comment by tolak** [comment]
I encountered this error on linux mint 18, the bug is still existing.

**Comment by Kubuxu** [comment]
Did you use 0.4.11-rc1?

**Comment by tolak** [comment]
No, it's 0.4.10 downloaded from here:https://dist.ipfs.io/#go-ipfs.

**Comment by Kubuxu** [comment]
It is fixed in 0.4.11-rc1. You can download it from: https://dist.ipfs.io/go-ipfs/v0.4.11-rc1

**Comment by tolak** [comment]
Thanks. I will try it!
