### ISSUE TITLE
docker: rename ipfs/go-ipfs:latest and/or add a latest stable image

### ISSUE THREAD

**Issue by chpio** [ipfs/go-ipfs#2888]
should be declared as the _dev_ build. i assumed it's the latest _working_ build, but it's not ;(

---

so i switched to an versioned image, but that's also not nice:
1. the base image isn't updating (the last versioned was built ~~2~~ a moth~~s~~ ago)
2. i have to track the versions (can't do a simple `docker-compose pull & systemctl restart ipfs` by hand or automatically)

it would be good that...
- the _latest_ image would be named _develop_ or something
- there would be a _latest_ (call it _stable_ or something) stable image

**Comment by whyrusleeping** [comment]
@chpio what is breaking on the latest docker image?

**Comment by chpio** [comment]
it was throwing an `Argument 'key' is required` on an `add` call, dunno what is causing it exactly (im using *js-ipfs-api*). after switching to the stable build it went away. https://github.com/ipfs/js-ipfs-api/issues/302

**Comment by whyrusleeping** [comment]
cc @lgierth

**Comment by lgierth** [comment]
Done, the images are being rebuilt right now: https://hub.docker.com/r/ipfs/go-ipfs/builds/

**Comment by lgierth** [comment]
This is now consistent with the original naming in jbenet/go-ipfs: latest=release-branch, release=release-branch, master=master-branch

**Comment by chpio** [comment]
still broken: 
![screenshot](https://cloud.githubusercontent.com/assets/545659/18794694/106664b8-81c1-11e6-9503-f0ddd90b9849.png)

**Comment by lgierth** [comment]
woops, thanks for raising this again - we forgot to push v0.4.3 to the release branch, which that image is based off. doing that now.

**Comment by lgierth** [comment]
reopening this issue because pushing to the release branch just triggered a build of the "latest" image... :S

**Comment by chpio** [comment]
also it isn't rebuilding on alpine updates, this should be fixed also
