### ISSUE TITLE
ipfs get /ipns/example.com fails with unexpected error

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3729]
Version: 0.4.6-rc1

Reproduction:
```
ipfs get /ipns/multiformats.io/                                 
Saving file(s) to .
 1024 B / 412.86 KB [>-----------------------------------------------------------------]   0.24% 0s
Error: open .: is a directory
```

**Comment by whyrusleeping** [comment]
Hrm... maybe the problem here is the trailing slash? 
I'm betting we take the last item in a strings.Split(path, "/"). which in this case would give us nothing.

**Comment by Kubuxu** [comment]
Yes it is, do we want to do something with it? Or just improve the error message?

I think it currently tries to save the content directly in current directory when it happens but errors out as current directory already exists.

**Comment by whyrusleeping** [comment]
@Kubuxu in the above example, we should trim the trailing slash, and save it into a folder named 'multiformats.io'

**Comment by whyrusleeping** [comment]
@Kubuxu progress here?

**Comment by Kubuxu** [comment]
I didn't touch it

**Comment by adamliesko** [comment]
Fixed in https://github.com/ipfs/go-ipfs/pull/4365, as my first contribution to go-ipfs.

**Comment by Stebalien** [comment]
This isn't fixed. The example in the first post exhibits the same behavior (it just says "Saving file(s) to multiformats.io" instead of "Saving file(s) to .").

**Comment by adamliesko** [comment]
Thanks @Stebalien, please see https://github.com/ipfs/go-ipfs/pull/4466 with proper fix.

**Comment by lidel** [comment]
I was unable to reproduce this with 0.4.22: 

```
> ipfs get /ipns/multiformats.io/
Saving file(s) to multiformats.io
 375.53 KiB / 375.53 KiB [================================================================================================] 100.00% 0s
```

I think Core API refactor fixed this some time ago, closing. Please reopen if still an issue.
