### ISSUE TITLE
$IPFS_PATH/api blocks use of `ipfs --local` until removed

### ISSUE THREAD

**Issue by elitak** [ipfs/go-ipfs#4214]
#### Description:
If the daemon gets killed violently, $IPFS_PATH/api and repo.lock are left behind. These get cleared on next start of the daemon, but if the user wishes to run any ipfs command using the `--local=true` flag before the next daemon startup, it will still try to use the defunct api endpoint instead of the local method. I think this behavior is probably unintended. Local commands should ignore and/or remove the api file in the IPFS_PATH.

**Comment by kevina** [comment]
A possible related issue is local command will just abort if the repo needs migration rather than offer to run the migration.

**Comment by Stebalien** [comment]
This has been fixed.

**Comment by elitak** [comment]
I'm running v0.4.23 and `ipfs --local=true id` still won't run if `/var/lib/ipfs/api` exists. I also need to run `ipfs repo fsck` to clear them when starting the daemon normally. This doesn't seem practical. What am I missing?

**Comment by hsanjuan** [comment]
I think this meant that this is fixed on master or 0.5.0-rc2.

**Comment by Stebalien** [comment]
It is.
