### ISSUE TITLE
IPFS swarm peers is "empty" and Webui not found on windows.

### ISSUE THREAD

**Issue by Marwen94** [ipfs/go-ipfs#4854]
**Version**
IPFS 0.4.13
 
**Type**
 bug ( not sure )

**Description**

I'm runing IPFS on Windows 10.

`ipfs daemon` is working fin. The problem is `ipfs swarm peers` is empty and I can not reach webui.
I get this message in my browser  :

>  ipfs resolve -r /ipfs/QmPhnvn747LqwPYMJmQVorMaGbMSgA7mRRoyyZYz3DoZRQ/: Failed to get block for QmPhnvn747LqwPYMJmQVorMaGbMSgA7mRRoyyZYz3DoZRQ

I have some ipfs bootstrap, when I try `ipfs swarm connect <bootstrap address>` I have this error : 

> Error: connect QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM failure: dial attempt failed: <peer.ID Q41PUB> --> <peer.ID SoLPpp> dial attempt failed: dial tcp6 [2604:a880:1:20::203:d001]:4001: connectex: A socket operation was attempted to an unreachable network.

In the other hand, I can connect in a local IPFS network with two local pc and it works fine, what means, I suppose, that my daemon works fine..

I'm working behind a firewall and I'm using specific ports for API and Gateway.

( I'm really sorry if my problem is not a bug and just a misunderstanding/missed point(s) from me)

Thank you !

**Comment by Stebalien** [comment]
So, your webui issues are due to the fact that you can't connect to other nodes to actually download the webui. Could you try go-ipfs [0.4.13-rc3](https://dist.ipfs.io/go-ipfs/v0.4.14-rc3). We've fixed a bunch of issues with dialing on Windows and this version may fix your bug. If not, we'll continue debugging.

**Comment by Marwen94** [comment]
Thank you for your respond @Stebalien 

Unfortunately, this issue does not seem resolved even with this version. I 'm still not able to connect to other peers. Have this message in my daemon log info :  

> Republisher failed to republish: failed to find any peer in table

When I force my node to connect to another bootstrap address I have a similar error message: 

>  Error: connect QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu failure: dial attempt failed: <peer.ID evzGNn> --> <peer.ID SoLSaf> dial attempt failed: dial tcp4 0.0.0.0:0->128.199.219.111:4001: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

One another thing about the bug conditions : I'm behind my work proxy.
Can this be the problem? How to configure IPFS to overcome it?

Thanks!

**Comment by Stebalien** [comment]
> One another thing about the bug conditions : I'm behind my work proxy.

Unfortunately, that's your problem. IPFS doesn't currently support SOCKS proxies. See: https://github.com/libp2p/go-libp2p/issues/286

If you can use a VPN, I recommend doing that. Otherwise, there's nothing you can do for now.

I'm closing this issue as a duplicate.
