### ISSUE TITLE
Couple errors on provider shutdown

### ISSUE THREAD

**Issue by ribasushi** [ipfs/go-ipfs#6985]
#### Version information:

Local build off https://github.com/ipfs/go-ipfs/commit/6ae79efc2f86

```
go-ipfs version: 0.5.0-dev
Repo version: 7
System version: amd64/darwin
Golang version: go1.14
```

#### Description:
The provider boots up when no daemon is running ( implicit offline mode ). Couple examples:

```
admin:~/devel/go-ipfs$ go run ./cmd/ipfs swarm peers
Error: this action must be run in online mode, try running 'ipfs daemon' first
2020-03-11T23:17:27.643+0100	ERROR	provider.queue	queue/queue.go:95	error deleting queue entry with key (), due to error (Writes are blocked, possibly due to DropAll or Close), stopping provider
github.com/ipfs/go-ipfs-provider/queue.(*Queue).work.func1
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:95
exit status 1
```

```
... | go run ./cmd/ipfs --encoding=json add --progress=false --chunker=rabin --trickle=false --raw-leaves=true --cid-version=1 
added bafybeicms4x7k62edxnnyysfufsotnivbfjoj6a7aouujcgg4l2kasnsey bafybeicms4x7k62edxnnyysfufsotnivbfjoj6a7aouujcgg4l2kasnsey
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4abe3b1]

goroutine 65 [running]:
github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(...)
	/Users/admin/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/skl/skl.go:86
< snip rest of separate issue >
	/Users/admin/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/keytransform/keytransform.go:71 +0x1d5
github.com/ipfs/go-ipfs-provider/queue.(*Queue).getQueueHead(0xc000398ff0, 0x0, 0x0, 0x0)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:137 +0x124
github.com/ipfs/go-ipfs-provider/queue.(*Queue).work.func1(0xc000398ff0)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:83 +0x782
created by github.com/ipfs/go-ipfs-provider/queue.(*Queue).work
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:73 +0x3f
exit status 2
```

**Comment by Stebalien** [comment]
Digging into this a bit, it looks like we _do_ need to start the queue, at least for _writing_. Given, that we might as well just start it completely.

However, we still need to fix these errors. That first one looks like a simple bug in the queue logic.

**Comment by Stebalien** [comment]
Ok, I've fixed the first issue.

**Comment by ribasushi** [comment]
The second issue is in full described in https://github.com/ipfs/go-ipfs/issues/6986. Closing this one as complete.

**Comment by hsanjuan** [comment]
I am still seeing this issue on master, in offline mode:

```
[14:39:39] ~/g/s/g/i/go-ipfs (master|…) $ 
ipfs cat zCT5htkdztJi3x4zBNHo8TRvGHPLTdHUdCLKgTGMgQcRKSLoWxK1
Cid4Data2020-03-13T14:40:10.986+0100    ERROR   provider.queue  queue/queue.go:93       error querying for head of queue: datastore closed, stopping provider
github.com/ipfs/go-ipfs-provider/queue.(*Queue).work.func1
        pkg/mod/github.com/ipfs/go-ipfs-provider@v0.4.1/queue/queue.go:93
```

(not panicking though).

**Comment by ribasushi** [comment]
>  in offline mode

> ipfs cat zCT...

@hsanjuan what activates offline mode in your failcase?

**Comment by hsanjuan** [comment]
> @hsanjuan what activates offline mode in your failcase?

I mean, without the daemon running. Or what do you mean?

**Comment by ribasushi** [comment]
> I mean, without the daemon running.

RIght, didn't realise this is what's happening ;)

**Comment by Stebalien** [comment]
Ah yeah, well I fixed the first issue but added another log line. Filed a new issue: https://github.com/ipfs/go-ipfs/issues/7015
